CREATE TRIGGER OnTeamDeletion_trigger
ON Team
AFTER DELETE
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM TeamStatistics
    WHERE TeamID IN (SELECT TeamID FROM DELETED);

    DELETE FROM Player
    WHERE TeamID IN (SELECT TeamID FROM DELETED);

	DELETE FROM Match
    WHERE Team1ID IN (SELECT TeamID FROM DELETED)
       OR Team2ID IN (SELECT TeamID FROM DELETED);


END;